### PR TITLE
hub-pa-api-code-review

### PR DESCRIPTION
**Pull request by uolter**
Initial setup project hub-pa. 
It's the big pot for tari tefa portal.
So far no service connection to azure have been defined: we do not have the subscription yet

### CODE REVIEW

**Comment by uolter** [comment]
> @uolter wait these changes..
> @GiovanniMancini we need also to set these permissions on all hub-pa-* repos:
> Screenshot 2021-03-09 at 15 24 42

@pasqualedevita mmm sorry I didn't get you ..... what should I have to do?

**Comment by pasqualedevita** [comment]
> > @uolter wait these changes..
> > @GiovanniMancini we need also to set these permissions on all hub-pa-* repos:
> > Screenshot 2021-03-09 at 15 24 42
> 
> @pasqualedevita mmm sorry I didn't get you ..... what should I have to do?

only wait that @GiovanniMancini adds required permissions to hup-pa-* repos.

Without these permissions I'm quit sure that when you create the pipeline pagopa-bot user can't create azure-devops webhook on git repos to catch PR triggers :)

**Comment by GiovanniMancini** [comment]
@pasqualedevita @uolter Thank you for pointing out, I have fixed permission issues as you suggested

> > > @uolter wait these changes..
> > > @GiovanniMancini we need also to set these permissions on all hub-pa-* repos:
> > > Screenshot 2021-03-09 at 15 24 42
> > 
> > 
> > @pasqualedevita mmm sorry I didn't get you ..... what should I have to do?
> 
> only wait that @GiovanniMancini adds required permissions to hup-pa-* repos.
> 
> Without these permissions I'm quite sure that when you create the pipeline pagopa-bot user can't create azure-devops webhook on git repos to catch PR triggers :)

**Review by pasqualedevita — COMMENTED** [review]
PR applied.
@GiovanniMancini you can start to work on code review pipeline creating a yaml file `.devops/code-review-pipelines.yml` in your repo https://github.com/pagopa/hub-pa-api
To complete deploy pipeline we need to have subscriptions created.

**Review by pasqualedevita — APPROVED** [review]

**Comment by pasqualedevita** [comment]
when subscriptions are ready we'll add the hub-pa-api-deploy pipeline

**Pull request merged**
